name: Build IFF

on:
  push:
    tags:
      - 'v*'   # triggers when you push a tag like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: g++ *.cpp -o iff
        
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: iff-${{ matrix.os }}
          path: iff